import { registerEnumType } from '@nestjs/graphql';

export enum AppEventAction {
  NOTIFICATION_CREATED = 'NOTIFICATION_CREATED',
  NOTE_CREATED = 'NOTE_CREATED',
  NOTE_UPDATED = 'NOTE_UPDATED',
  NOTE_DELETED = 'NOTE_DELETED',
  NOTE_SHARED = 'NOTE_SHARED',
  CALENDAR_EVENT_CREATED = 'CALENDAR_EVENT_CREATED',
  CALENDAR_EVENT_UPDATED = 'CALENDAR_EVENT_UPDATED',
  CALENDAR_EVENT_DELETED = 'CALENDAR_EVENT_DELETED',
}

registerEnumType(AppEventAction, { name: 'AppEventAction' });
